2.8/ckan-base/setup/prerun.py
I think the current check doesn't work with e.g. my setup because of the whitespace:
```
paster --plugin=ckan user ckan_admin -c $CKAN_INI
2018-08-03 14:49:37,652 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2018-08-03 14:49:37,665 DEBUG [ckanext.harvest.model] Harvest tables already exist
2018-08-03 14:49:38,220 DEBUG [ckanext.harvest.model] Harvest tables already exist
User:
None
```
=> Fix sysadmin creation for ckan-2.8

.env.example, ckan-base/2.7/Dockerfile, ckan-base/2.8/Dockerfile, ckan/Dockerfile, ckan/Dockerfile.dev, docker-compose.dev.yml, docker-compose.yml
Various user actions result in server crash (in the "production" container) with the following log:
```
ckan          | File '/usr/lib/python2.7/site-packages/tzlocal/unix.py', line 123 in get_localzone
ckan          |   _cache_tz = _get_localzone()
ckan          | File '/usr/lib/python2.7/site-packages/tzlocal/unix.py', line 117 in _get_localzone
ckan          |   raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
ckan          | UnknownTimeZoneError: 'Can not find any timezone configuration'
```
This is because no timezone is set in the alpine image.
This PR fixes that by
1. Installing timezone database in ckan-base.
2. Adding a variable `TZ` to `.env.example` (default=UTZ).
3. Setting the timezone in images ckan and ckan-dev.
=> timezone issue

docker-compose.yml
This is opinionated. For me it seems clear that the Solr index in production should not be lost when the container is re-created. So I added a volume for the index. Feel free to close without comment, if you see things differently.
=> added solr volume

ckan-base/2.8/Dockerfile
Build of `ckan-base` fails because `py-geos` is not an [Alpine package](https://pkgs.alpinelinux.org/packages) anymore. Really, I searched extensively. [Google cache](https://webcache.googleusercontent.com/search?q=cache:dLIhMtPpta4J:https://pkgs.alpinelinux.org/package/edge/testing/x86/py-geos+&cd=8&hl=de&ct=clnk&gl=ch&client=firefox-b-d) tells me that it still was on Juli 5th.
Since this package contained "geos Python bindings", and geos Python bindings are provided by [Shapely](https://pypi.org/project/Shapely/), chances are it is not necessary. Container builds and seems to run OK with [ckanext-spatial](https://github.com/ckan/ckanext-spatial) enabled.
=> removed py-geos@testing from ckan-base Dockerfile

.env.example
Some extensions require config variables at load time, e.g. [ckanext-scheming](https://github.com/ckan/ckanext-scheming). If these variables are supplied via [ckanext-envvars](https://github.com/okfn/ckanext-envvars), envvars has to be loaded before the respective plugins. If that is not the case, ckanext-scheming for example will not load its schemata.
=> envvars to beginning of plugin list

ckan-base/setup/prerun.py, ckan-base/setup/start_ckan.sh
A custom plugin that implements [IConfigurable](https://docs.ckan.org/en/2.8/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IConfigurable) might require the database when it is loaded, in particular when it is loaded by a paster command such as `paster db init`.
In the current code this leads to startup failure.
This PR solves the problem by moving the update of the list of plugins from `start_ckan.py` into a function in `prerun.py` where it is called **after** `init_db()`.
=> fixed init order

datapusher/Dockerfile
Fix a parse error when building: `ERROR: Dockerfile parse error line 39: unknown instruction: 5CMD`
=> Fix typo in datapusher Dockerfile

ckan-base/setup/start_ckan.sh, ckan-dev/setup/start_ckan_development.sh
This avoids the storage folder (/var/lib/ckan/storage) being owned by root
This is an alternative to #42
=> Run the prerun.py script as ckan user

ckan-dev/setup/start_ckan_development.sh
Those config keys are wrong.
After starting in development mode and checking test-core.ini you can see that this leads to new config values with the wrong names being created instead of updating existing ones.
=> fix config key names in start_ckan_development.sh

ckan-base/setup/start_ckan.sh
- ckan closes connection when request header size exceeds 4069 bytes
- this can easily happen when requests include long cookies (e.g. oauth tokens) etc.
- max setting for buffer size would be 65535 bytes, see https://uwsgi-docs.readthedocs.io/en/latest/ThingsToKnow.html
fixes #50
=> set uwsgi buffer size from 4096 to 32768

datapusher/Dockerfile
Without this installed messytables throws `ImportError: failed to find libmagic.`
=> install libmagic in datapusher container

ckan-base/2.7/Dockerfile, ckan-base/2.8/Dockerfile, ckan-base/2.9/Dockerfile.py2
We need to pin pip version from CKAN 2.8 because pip no longer support python 2
https://pip.pypa.io/en/stable/
=> pip 21 no longer support python 2.7

ckan-dev/2.9/setup/start_ckan_development-py2.sh
The current setup (where we always install from `requirements.txt`) means that if we try to run a ckan-dev container with a local CKAN install, we end up with a broken install because the python3 requirements are installed on python2. This switches it so that when we are running CKAN 2.9 on python2, we first look for `requirements-py2.txt` and fall back to `requirements.txt` if it does not exist.
=> 2.9/py2: Prefer requirements-py2.txt to requirements.txt if both exist

.env.example
https://github.com/okfn/docker-ckan/issues/86
Recent versions (2.1.1) of docker-compose error with "key cannot contain
a space". Any environment variable with spaces should be quoted.
=> Quote spaces in env variables

datapusher/Dockerfile
Minor update of Datapusher from 0.0.17 to 0.0.18. The version 0.0.17 is failing to build, failing at the cryptography dependency:
```
cecivieira@cecivieira-Inspiron-7380:~/Projetos/docker-ckan$ docker-compose build
solr uses an image, skipping
redis uses an image, skipping
Building datapusher
Step 1/13 : FROM alpine:3.13
3.13: Pulling from library/alpine
72cfd02ff4d0: Pull complete
Digest: sha256:100448e45467d4f3838fc8d95faab2965e22711b6edf67bbd8ec9c07f612b553
Status: Downloaded newer image for alpine:3.13
---> 6b5c5e00213a
Step 2/13 : MAINTAINER Open Knowledge Foundation
---> Running in 8244d80caf3b
Removing intermediate container 8244d80caf3b
---> 41d69b0a46b3
Step 3/13 : ENV APP_DIR=/srv/app
---> Running in 9ba5a72c2403
Removing intermediate container 9ba5a72c2403
---> 1ec74b69b6da …
```
=> Update datapusher version to the latest one (0.0.18) in its Dockerfile

datapusher/Dockerfile
Error building the image from the repo
- Clone the repo
- Run `cp .env.example .env`
- Run `docker-compose -f docker-compose.dev.yml up --build`
These steps end up giving this error
```
#0 37.97   writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
#0 37.97   copying src/cryptography/py.typed -> build/lib.linux-x86_64-cpython-38/cryptography
#0 37.97   copying src/cryptography/hazmat/bindings/_openssl.pyi -> build/lib.linux-x86_64-cpython-38/cryptography/hazmat/bindings
#0 37.97   creating build/lib.linux-x86_64-cpython-38/cryptography/hazmat/bindings/_rust
#0 37.97   copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-x86_64-cpython-38/cryptography/hazmat/bindings/_rust
#0 37.97   copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> …
```
=> fix: fix criptography problem

ckan-base/2.8/Dockerfile, ckan-base/2.9/Dockerfile.py2
Package `mailcap` provides `/etc/mime.types` required by the mimetypes module. The python3 images already include it via `uwsgi`.
=> Add mailcap to python2 docker images

.env.example, ckan-base/2.10/Dockerfile, ckan-base/2.10/setup/start_ckan.sh
If the `expire_api_token` plugin is enabled we need to define `expires_in` and `unit` parameters
The environment variables `DATAPUSHER_TOKEN_EXPIRES_IN` and `DATAPUSHER_TOKEN_EXPIRES_UNIT` are proposed to fix a build error
<pre>
Traceback (most recent call last):
ckan-dev4      |   File "/usr/bin/ckan", line 8, in <module>
ckan-dev4      |     sys.exit(ckan())
ckan-dev4      |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
ckan-dev4      |     return self.main(*args, **kwargs)
ckan-dev4      |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
ckan-dev4      |     rv = self.invoke(ctx)
ckan-dev4      |   File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
ckan-dev4      |     return …
=> Allow required params for token creation

ckan-base/2.10/setup/start_ckan.sh, ckan-dev/2.10/setup/start_ckan_development.sh
Fixes error `ckan.logic.ValidationError: None - {'expires_in': ['Missing value'], 'unit': ['Missing value']}`
=> Api token expire for ckan 10 dev

.github/workflows/publish-docker.yml
If CKAN 2.8 fails to build, CKAN 2.9 will not continue.
We need to continue.
=> Continue builds if any version fails

.github/workflows/publish-docker.yml
If CKAN 2.8 fails to build, CKAN 2.9 will not continue.
We need to continue.
=> Fix continue on error
